### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by azahmed096** [oSoc18/vlaio-network-backend#13]

**Comment by azahmed096** [comment]
First create a super user: `python .\manage.py createsuperuser`

Then go to the `/admin/` endpoint (not api but from browser). For example http://127.0.0.1:8000/admin/

Here under _AUTHENTICATION AND AUTHORIZATION_ you press +Add next to _User_.
Or you can go to the _User_ link to manage existing users.

# API

## Login
POST `/auth/login/`
with body: 
```json
{
	"username": "usertest",
	"password": "userpassword"
}```

the response is a json with the token
```json
{
   "token": "518ba9f51cb5ba0b37f75a64ba8fdb9679294d00"
}
```
## profile info
To get more details about you should use `/auth/my-profile/` endpoints with get


## token
After recieving a token you put it in the `Authorization` header like this `Token 518ba9f51cb5ba0b37f75a64ba8fdb9679294d00` (there is a space between _Token_ and the actual token).

**Comment by archived-m** [comment]
@azahmed096 This should include and endpoint for creating new users (for admins only).
`POST /user`
I'd create a new issue for managing user accounts and roles

**Comment by archived-m** [comment]
Also, please include user information in the login response so we can display the first name, last name and email if need be.
